# Generated by Django 3.1.5 on 2021-01-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20210130_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_number',
            field=models.CharField(default=1, editable=False, max_length=32),
        ),
    ]
