# Generated by Django 3.1.5 on 2021-01-30 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('wishlist', '0003_wishlist_wishlist_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='item_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_number',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
