# Generated by Django 3.1.5 on 2021-01-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_credit',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
